version: '3.8'

services:
  web:
    build: .
    container_name: php-apache-app
    ports:
      - "8080:80"  # Redirige le port 8080 de ta machine vers le port 80 du conteneur
    volumes:
      - ./app:/var/www/html  # Monte le répertoire local de ton application dans le conteneur
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Mot de passe pour l'utilisateur root
      MYSQL_DATABASE: mydatabase         # Nom de la base de données
    ports:
      - "3306:3306"  # Redirige le port 3306 pour se connecter à la base de données depuis l'extérieur
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

